// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e3f8daf1-605e-477e-8035-ceda9b68726a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BnwsnCNXC",
    "aws_user_pools_web_client_id": "d74knlbc099rniuqmoqb2tagp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ovwbuoocrvcwrapwkhwhpiq6vq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
